//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationProject.Registration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Registration.IRegistration")]
    public interface IRegistration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistration/Register", ReplyAction="http://tempuri.org/IRegistration/RegisterResponse")]
        string Register(string firstId, string secondId, string thirdId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistration/Register", ReplyAction="http://tempuri.org/IRegistration/RegisterResponse")]
        System.Threading.Tasks.Task<string> RegisterAsync(string firstId, string secondId, string thirdId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistration/Log", ReplyAction="http://tempuri.org/IRegistration/LogResponse")]
        void Log(string anchor, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistration/Log", ReplyAction="http://tempuri.org/IRegistration/LogResponse")]
        System.Threading.Tasks.Task LogAsync(string anchor, string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationChannel : RegistrationProject.Registration.IRegistration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationClient : System.ServiceModel.ClientBase<RegistrationProject.Registration.IRegistration>, RegistrationProject.Registration.IRegistration {
        
        public RegistrationClient() {
        }
        
        public RegistrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Register(string firstId, string secondId, string thirdId, string user) {
            return base.Channel.Register(firstId, secondId, thirdId, user);
        }
        
        public System.Threading.Tasks.Task<string> RegisterAsync(string firstId, string secondId, string thirdId, string user) {
            return base.Channel.RegisterAsync(firstId, secondId, thirdId, user);
        }
        
        public void Log(string anchor, string status) {
            base.Channel.Log(anchor, status);
        }
        
        public System.Threading.Tasks.Task LogAsync(string anchor, string status) {
            return base.Channel.LogAsync(anchor, status);
        }
    }
}
